name: flutter_rpg_project
description: "Projeto base de RPG em Flutter — arquitetura modular por features."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Navegação
  go_router: ^14.2.0

  # Persistência (banco de dados local)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # Autenticação local (hashing de senha)
  crypto: ^3.0.3

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/icons/
